### ISSUE TITLE
Support git-plugin 2.3

### ISSUE THREAD

**Issue by guilhem** [jenkinsci/debian-package-builder-plugin#24]
Here is error I get when trying to update changelog from git with latest master.

```
FATAL: hudson.plugins.git.GitSCM.createClient(Lhudson/model/BuildListener;Lhudson/EnvVars;Lhudson/model/AbstractBuild;)Lorg/jenkinsci/plugins/gitclient/GitClient;
java.lang.NoSuchMethodError: hudson.plugins.git.GitSCM.createClient(Lhudson/model/BuildListener;Lhudson/EnvVars;Lhudson/model/AbstractBuild;)Lorg/jenkinsci/plugins/gitclient/GitClient;
	at ru.yandex.jenkins.plugins.debuilder.ChangesExtractor.getChangesFromGit(ChangesExtractor.java:133)
	at ru.yandex.jenkins.plugins.debuilder.ChangesExtractor.getChanges(ChangesExtractor.java:48)
	at ru.yandex.jenkins.plugins.debuilder.DebianPackageBuilder.generateChangelog(DebianPackageBuilder.java:197)
	at ru.yandex.jenkins.plugins.debuilder.DebianPackageBuilder.perform(DebianPackageBuilder.java:110)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:772)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:535)
	at hudson.model.Run.execute(Run.java:1732)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:234)
```

**Comment by aakhmerov** [comment]
I have that too

**Comment by pupssman** [comment]
Looks like a simple fix to me. Going 2 look into the issue in a couple days.

**Comment by aakhmerov** [comment]
looks like a simple fix indeed.

**Comment by aakhmerov** [comment]
thanks for merge guys, could we release it somehow? :)

**Comment by mavlyutov** [comment]
I'll release it today
